name: QA Tests Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: qa_tests_image
      IMAGE_TAG: latest
      REPORT_DIR: allure-report

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG

  smoke-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run Smoke Tests
        run: |
          docker run --rm -v $PWD/allure-report:/app/allure-report ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          sh -c "pytest tests/smoke --alluredir=allure-report --tb=short"

  integration-tests:
    runs-on: ubuntu-latest
    needs: smoke-tests
    steps:
      - uses: actions/checkout@v3
      - name: Run Integration Tests
        run: |
          docker run --rm -v $PWD/allure-report:/app/allure-report ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          sh -c "pytest tests/integration --alluredir=allure-report --tb=short"

  regression-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v3
      - name: Run Regression Tests
        run: |
          docker run --rm -v $PWD/allure-report:/app/allure-report ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          sh -c "pytest tests/regression --alluredir=allure-report --tb=short"

  allure-report:
    runs-on: ubuntu-latest
    needs: [smoke-tests, integration-tests, regression-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Generate Allure HTML report
        run: |
          docker run --rm -v $PWD/allure-report:/app/allure-report -v $PWD/allure-report/allure-html:/app/allure-html \
          ghcr.io/allure/allure:2.22.1 generate /app/allure-report -o /app/allure-html
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/allure-html
