name: CI with Selenium, Pytest and Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Smoke tests
        run: pytest -m smoke --alluredir=allure-results

      - name: Upload Allure Results (smoke)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: allure-results

  integration:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Integration tests
        run: pytest -m integration --alluredir=allure-results

      - name: Upload Allure Results (integration)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-integration
          path: allure-results

  regression:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Regression tests
        run: pytest -m regression --alluredir=allure-results

      - name: Upload Allure Results (regression)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression
          path: allure-results

  allure-report:
    runs-on: ubuntu-latest
    needs: regression
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-regression
          path: allure-results

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-pages:
    runs-on: ubuntu-latest
    needs: allure-report
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: deploy-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4